url: /
name: Crowded
permalink: /:title

markdown: kramdown
highlighter: rouge
permalink: pretty
plugins: plugins
paginate: 6

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

team:
  - name: Josh Minnie
    aka: TruePico
    role: founder
    avatar: https://avatars.io/twitter/TheTruePico
    bio: I live and breath the web. I love spending time with my family and gaming. If I'm not doing any of those, I'm probably sleeping.
    social:
      twitter: TheTruePico
      github: joshminnie
      instagram: joshminnie
      xbox: TruePico
  - name: Josh Pennington
    aka: joshpennington
    role: admin
    avatar: https://pbs.twimg.com/profile_images/989535033596624896/lrL08dmY.jpg
    bio: PHP developer by day, geek at night. I watch too much Doctor Who.
    social:
      twitter: joshpennington
      github: joshpennington
      instagram: joshpennington/
      youtube: spartan8103
      xbox: Spartan8103
      stackoverflow: 365709
  - name: Keith Sayer
    aka: Vickriman
    role: admin
    avatar: https://avatars.io/twitter/vickriman
    social:
      twitter: vickriman
  - name: Jason Minnie
    aka: Firestarter
    role: moderator
    avatar: https://avatars.io/twitter/slick150_2000
    social:
      twitter: slick150_2000
